"""Grounded explanations — answering questions from the verified computed state.

This is the G4 / C-GROUNDED-EXPLANATION layer. An ``Explainer`` answers a natural-language
question about a solved problem by (1) matching it to an intent, (2) reading the relevant
*verified* ``Quantity`` objects, and (3) composing an explanation whose every numeric or
symbolic token is copied from those quantities. No value is invented, and the geometric
intuition attached to an answer is *selected by* the verified result (e.g. the "saddle"
wording is used only when the engine classified the point as a saddle), so an answer can
never assert something the engine's results contradict.

Because the answer is built from the verified state rather than generated by a model, it is
grounded by construction and needs no network or API key. Every answer reports which
quantities it drew from (``grounded_in``) so the grounding is checkable (see the G4 check).
"""

from __future__ import annotations

from .result import Solution


def _fmt_point(p, nd=3):
    return "(" + ", ".join(f"{float(c):.{nd}g}" for c in p) + ")"


class Explainer:
    def __init__(self, solution: Solution):
        self.sol = solution
        self.by_name = {q.name: q for q in solution.quantities}

    def has(self, name: str) -> bool:
        q = self.by_name.get(name)
        return bool(q and q.verified)

    def q(self, name: str):
        return self.by_name[name]

    # --- public ----------------------------------------------------------------

    def answer(self, question: str) -> dict:
        text = question.lower()
        for keywords, handler in self._intents():
            if any(k in text for k in keywords):
                composed = handler()
                if composed:
                    body, sources = composed
                    return self._wrap(question, body, sources)
        # fallback: a grounded overview of everything computed
        body, sources = self._overview()
        return self._wrap(question, body, sources)

    def _wrap(self, question, body, sources):
        return {
            "question": question,
            "answer": body,
            "grounded_in": sources,
            "area": self.sol.area,
            "problem_id": self.sol.problem_id,
        }

    # --- intents (checked in order) --------------------------------------------

    def _intents(self):
        return [
            (("gradient", "steepest", "slope"), self._gradient),
            (("hessian", "curvature", "concav"), self._hessian),
            (("saddle", "critical", "minimum", "maximum", "max ", "min ", "stationary",
              "extrem"), self._critical),
            (("descent", "converge", "trajectory", "iterat"), self._descent),
            (("lagrange", "constraint", "constrained", "lambda", "multiplier"), self._lagrange),
            (("diverg", "source", "sink", "expand", "compress"), self._divergence),
            (("curl", "rotat", "circulat", "swirl", "vortic", "spin"), self._curl),
            (("determinant", "det", "area", "volume", "scale factor"), self._determinant),
            (("eigen", "invariant direction"), self._eigen),
            (("singular", "svd", "ellipsoid", "principal ax"), self._svd),
            (("equilibri", "fixed point", "fixed-point", "rest point", "steady state"),
             self._fixed_points),
            (("stabilit", "stable", "unstable", "spiral", "node", "phase portrait",
              "classif", "sink", "source"), self._stability),
            (("trajector", "flow", "integral curve", "orbit", "evolv", "solution curve",
              "where does it go", "settle"), self._trajectory),
            (("chaos", "chaotic", "sensitive", "lyapunov", "attractor", "butterfly"),
             self._chaos),
        ]

    # --- composers (return (text, [source names]) or None) ---------------------

    def _gradient(self):
        if not self.has("gradient"):
            return None
        g = self.q("gradient")
        text = (f"The gradient is {g.display}. It points in the direction of steepest "
                "increase of f, and its length is how steep that climb is. Where the "
                "surface is flat — at a critical point — the gradient is the zero vector.")
        srcs = ["gradient"]
        if self.has("critical_points"):
            cps = self.q("critical_points").value
            if cps:
                text += (" Here ∇f = 0 at "
                         + "; ".join(_fmt_point(c["point"]) for c in cps) + ".")
                srcs.append("critical_points")
        return text, srcs

    def _hessian(self):
        if not self.has("hessian"):
            return None
        h = self.q("hessian")
        text = (f"The Hessian is {h.display}. Its eigenvalues are the curvatures of the "
                "surface along its principal directions: all positive means a bowl (a "
                "minimum), all negative a dome (a maximum), and mixed signs a saddle.")
        return text, ["hessian"]

    def _critical(self):
        if not self.has("critical_points"):
            # optimization problems expose the minimum instead
            if self.has("minimum"):
                return self._minimum()
            return None
        cps = self.q("critical_points").value
        if not cps:
            return "There are no critical points of f in the region shown.", ["critical_points"]
        intuition = {
            "minimum": "a minimum — the surface curves upward in every direction",
            "maximum": "a maximum — the surface curves downward in every direction",
            "saddle": "a saddle — the surface curves up in one direction and down in another",
            "degenerate": "a degenerate critical point — the second-derivative test is inconclusive",
        }
        parts = []
        for c in cps:
            parts.append(f"{_fmt_point(c['point'])} is {intuition.get(c['type'], c['type'])} "
                         f"(f = {c['f']:.3g})")
        return "The critical points, where ∇f = 0: " + "; ".join(parts) + ".", ["critical_points"]

    def _minimum(self):
        if not self.has("minimum"):
            return None
        m = self.q("minimum").value
        return (f"The minimum is at {_fmt_point(m['point'])}, where f = {m['f']:.4g}. It is a "
                "true minimum: the gradient vanishes there and the Hessian is positive-"
                f"definite (eigenvalues {', '.join(f'{e:.3g}' for e in m['hessian_eigenvalues'])}, "
                "all positive).", ["minimum"])

    def _descent(self):
        if not self.has("descent"):
            return None
        d = self.q("descent").value
        f0, f1 = d["f_values"][0], d["f_values"][-1]
        text = (f"Gradient descent started at {_fmt_point(d['start'])} and, following −∇f "
                f"downhill, reached {_fmt_point(d['final_point'])} after {len(d['points'])-1} "
                f"steps. The objective fell from {f0:.4g} to {f1:.4g} and never increased "
                f"along the way; the gradient there has length {d['final_gradient_norm']:.2g}, "
                "so it has essentially settled at the bottom.")
        srcs = ["descent"]
        if self.has("minimum"):
            m = self.q("minimum").value
            text += f" That bottom is the minimum at {_fmt_point(m['point'])}."
            srcs.append("minimum")
        return text, srcs

    def _lagrange(self):
        if not self.has("constrained_optimum"):
            return None
        o = self.q("constrained_optimum").value
        return (f"The constrained optimum is at {_fmt_point(o['point'])}, where f = "
                f"{o['f']:.4g}, with Lagrange multiplier λ = {o['lambda']:.4g}. At that point "
                "the constraint is satisfied and ∇f is parallel to ∇g (that is what λ "
                "measures) — geometrically, the level set of f is tangent to the constraint "
                "curve there.", ["constrained_optimum"])

    def _divergence(self):
        if not self.has("divergence"):
            return None
        dv = self.q("divergence")
        val = dv.value
        text = f"The divergence is div F = {val}. "
        try:
            num = float(val)
            if num > 1e-9:
                text += ("It is positive, so the field has net outflow — the flow spreads "
                         "outward, like a source.")
            elif num < -1e-9:
                text += ("It is negative, so the field has net inflow — the flow contracts "
                         "inward, like a sink.")
            else:
                text += "It is zero, so the flow neither expands nor compresses volume."
        except (TypeError, ValueError):
            text += "It measures how much the field spreads out from each point."
        return text, ["divergence"]

    def _curl(self):
        if not self.has("curl"):
            return None
        c = self.q("curl")
        text = f"The curl is {c.display}. "
        vals = c.value if isinstance(c.value, list) else [c.value]
        try:
            mags = [abs(float(v)) for v in vals]
            if max(mags) > 1e-9:
                text += ("It is non-zero, so the field rotates — a paddle wheel dropped in "
                         "would spin, and its axis is the curl's direction.")
            else:
                text += "It is zero, so the field is irrotational — no local swirling."
        except (TypeError, ValueError):
            text += "It measures the local rotation of the field."
        return text, ["curl"]

    def _determinant(self):
        if not self.has("determinant"):
            return None
        d = self.q("determinant")
        val = float(d.value)
        if abs(val) < 1e-12:
            meaning = "zero, so the transformation collapses space onto a lower dimension (it is singular)"
        elif val < 0:
            meaning = f"{val:.4g}, so it scales area/volume by {abs(val):.4g} and flips orientation"
        else:
            meaning = f"{val:.4g}, so it scales area/volume by that factor and preserves orientation"
        return f"The determinant is {meaning}.", ["determinant"]

    def _eigen(self):
        if not self.has("eigen"):
            return None
        e = self.q("eigen").value
        parts = []
        for p in e["pairs"]:
            lam = p["eigenvalue"]
            lam_s = f"{lam[0]:.3g}" if abs(lam[1]) < 1e-9 else f"{lam[0]:.3g}{lam[1]:+.3g}i"
            v = [c[0] for c in p["eigenvector"]]
            parts.append(f"λ = {lam_s} along {_fmt_point(v)}")
        text = ("The eigenvalues and their invariant directions: " + "; ".join(parts)
                + ". A vector on such a direction is only stretched by λ, not rotated.")
        if e.get("defective"):
            text += (" This matrix is defective: it has fewer independent eigenvectors than "
                     "eigenvalues, so it cannot be diagonalized (a shear is the classic case).")
        return text, ["eigen"]

    def _svd(self):
        if not self.has("svd"):
            return None
        s = self.q("svd").value
        sv = ", ".join(f"{v:.4g}" for v in s["singular_values"])
        return (f"The singular values are {sv}. They are the lengths of the semi-axes of the "
                "ellipsoid that the transformation turns the unit sphere into; the "
                "corresponding singular vectors are those axes' directions. The largest is "
                "how much the map can stretch a unit vector, the smallest how much it can "
                "shrink one.", ["svd"])

    def _fixed_points(self):
        if not self.has("fixed_points"):
            return None
        fps = self.q("fixed_points").value
        if not fps:
            return "This system has no equilibria (points where the flow stops) in the region shown.", ["fixed_points"]
        parts = [f"{_fmt_point(fp['point'])} — {fp['type']}" for fp in fps]
        return ("The equilibria, where ẋ = F(x) = 0 (the flow is momentarily at rest): "
                + "; ".join(parts) + ". Their type says what the flow does nearby.",
                ["fixed_points"])

    def _stability(self):
        if not self.has("stability"):
            # a system may expose fixed_points without a separate stability read
            return self._fixed_points()
        entries = self.q("stability").value
        if not entries:
            return "There are no equilibria to classify in the region shown.", ["stability"]
        parts = []
        for e in entries:
            eig = ", ".join(
                (f"{v[0]:.3g}" if abs(v[1]) < 1e-9 else f"{v[0]:.3g}{v[1]:+.3g}i")
                for v in e["eigenvalues"])
            parts.append(f"{_fmt_point(e['point'])} is a {e['type']} (Jacobian eigenvalues {eig})")
        return ("Stability comes from the Jacobian's eigenvalues at each equilibrium: "
                + "; ".join(parts)
                + ". Negative real parts pull the flow in, positive push it out, and an "
                "imaginary part means it spirals.", ["stability"])

    def _trajectory(self):
        names = [q.name for q in self.sol.quantities if q.name.startswith("trajectory") and q.verified]
        if not names:
            return None
        t = self.q(names[0]).value
        text = (f"A trajectory starting at {_fmt_point(t['x0'])} follows the flow to "
                f"{_fmt_point(t['final_point'])} over t ∈ [{t['t_span'][0]:g}, {t['t_span'][1]:g}]. "
                "Each such curve is a solution of the system — the path a point takes as it "
                "moves along the field.")
        srcs = [names[0]]
        if self.has("fixed_points"):
            fps = self.q("fixed_points").value
            attractors = [fp for fp in fps if "stable" in fp["type"] and "unstable" not in fp["type"]]
            if attractors:
                text += (" It is drawn toward the "
                         + ", ".join(f"{fp['type']} at {_fmt_point(fp['point'])}" for fp in attractors) + ".")
                srcs.append("fixed_points")
        return text, srcs

    def _chaos(self):
        if not self.has("separation"):
            return None
        s = self.q("separation").value
        lam = s["finite_time_lyapunov"]
        chaotic = lam > 1e-3
        text = (f"Sensitive dependence is measured directly: two trajectories starting "
                f"{s['initial_separation']:.1e} apart grow to {s['final_separation']:.3g} apart "
                f"by t = {s['t_span'][1]:g}, a mean exponential rate of about {lam:+.3f} per unit "
                "time (a finite-time Lyapunov estimate). ")
        text += ("A positive rate means nearby states pull apart exponentially — the hallmark "
                 "of chaos: the long-term path is unpredictable even though every step is "
                 "deterministic." if chaotic else
                 "This rate is not positive, so nearby trajectories stay close — this behaviour "
                 "is regular, not chaotic.")
        return text, ["separation"]

    def _overview(self):
        lines, srcs = [], []
        for q in self.sol.quantities:
            if q.verified:
                lines.append(f"• {q.name.replace('_', ' ')}: {q.display}")
                srcs.append(q.name)
        return ("Here is what the engine computed for this problem (every value verified):\n"
                + "\n".join(lines)), srcs
